version: '1'
services:
  redis:
    image: redis:redis-cache
    ports:
      - "6379:6379"
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: hw13_base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data